# Generated by Django 3.1.3 on 2021-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrierfscode', models.CharField(max_length=50)),
                ('flightnumber', models.CharField(max_length=50)),
                ('departureairportfscode', models.CharField(max_length=50)),
                ('formatteddeparture', models.CharField(max_length=50)),
                ('arrivalairportfscode', models.CharField(max_length=50)),
                ('formattedarrival', models.CharField(max_length=50)),
                ('edit', models.BooleanField(default=False)),
            ],
        ),
    ]
