# Generated by Django 3.1.3 on 2021-01-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flightday',
            field=models.CharField(default='', max_length=50),
        ),
    ]
