# Generated by Django 3.1.3 on 2021-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_flight_flightday'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flightequipmentiatacode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
